export const animations = {
    dancar: {
        type: 'normal',
        dict: 'rcmnigel1bnmt_1b',
        anim: 'dance_flag_t1',
        flag: 1,
    },
    dancar2: {
        type: 'normal',
        dict: 'mp_safehouse',
        anim: 'lap_dance_girl',
        flag: 1,
    },
    dancar3: {
        type: 'normal',
        dict: 'misschinese2_crystalmazemcs1_cs',
        anim: 'dance_flag_t1',
        flag: 1,
    },
    dancar4: {
        type: 'normal',
        dict: 'mini@strip_club@private_dance@part1',
        anim: 'priv_dance_p1',
        flag: 1,
    },
    dancar5: {
        type: 'normal',
        dict: 'mini@strip_club@private_dance@part2',
        anim: 'priv_dance_p2',
        flag: 1,
    },
    dancar6: {
        type: 'normal',
        dict: 'mini@strip_club@private_dance@part3',
        anim: 'priv_dance_p3',
        flag: 1,
    },
    dancar7: {
        type: 'normal',
        dict: 'special_ped@mountain_dancer@monologue_2@monologue_2a',
        anim: 'mnt_dnc_angel',
        flag: 1,
    },
    dancar8: {
        type: 'normal',
        dict: 'special_ped@mountain_dancer@monologue_3@monologue_3a',
        anim: 'mnt_dnc_buttwag',
        flag: 1,
    },
    dancar9: {
        type: 'normal',
        dict: 'missfbi3_sniping',
        anim: 'dance_m_default',
        flag: 1,
    },
    dancar10: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@black_madonna_entourage@',
        anim: 'hi_dance_facedj_09_v2_male^5',
        flag: 1,
    },
    dancar11: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_female^1',
        flag: 1,
    },
    dancar12: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_female^2',
        flag: 1,
    },
    dancar13: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_female^3',
        flag: 1,
    },
    dancar14: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_female^4',
        flag: 1,
    },
    dancar15: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_female^5',
        flag: 1,
    },
    dancar16: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_female^6',
        flag: 1,
    },
    dancar17: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_male^1',
        flag: 1,
    },
    dancar18: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_male^2',
        flag: 1,
    },
    dancar19: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_male^3',
        flag: 1,
    },
    dancar20: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_male^4',
        flag: 1,
    },
    dancar21: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_male^5',
        flag: 1,
    },
    dancar22: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v1_male^6',
        flag: 1,
    },
    dancar23: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^1',
        flag: 1,
    },
    dancar24: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^2',
        flag: 1,
    },
    dancar25: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^3',
        flag: 1,
    },
    dancar26: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^4',
        flag: 1,
    },
    dancar27: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^5',
        flag: 1,
    },
    dancar28: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^6',
        flag: 1,
    },
    dancar29: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_male^1',
        flag: 1,
    },
    dancar30: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_male^2',
        flag: 1,
    },
    dancar31: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_male^3',
        flag: 1,
    },
    dancar32: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_male^4',
        flag: 1,
    },
    dancar33: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_male^5',
        flag: 1,
    },
    dancar34: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_male^6',
        flag: 1,
    },
    dancar35: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_female^1',
        flag: 1,
    },
    dancar36: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_female^2',
        flag: 1,
    },
    dancar37: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_female^3',
        flag: 1,
    },
    dancar38: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_female^4',
        flag: 1,
    },
    dancar39: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_female^5',
        flag: 1,
    },
    dancar40: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_female^6',
        flag: 1,
    },
    dancar41: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_male^1',
        flag: 1,
    },
    dancar42: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_male^2',
        flag: 1,
    },
    dancar43: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_male^3',
        flag: 1,
    },
    dancar44: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_male^4',
        flag: 1,
    },
    dancar45: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_male^5',
        flag: 1,
    },
    dancar46: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v1_male^6',
        flag: 1,
    },
    dancar47: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_female^1',
        flag: 1,
    },
    dancar48: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_female^2',
        flag: 1,
    },
    dancar49: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_female^3',
        flag: 1,
    },
    dancar50: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_female^4',
        flag: 1,
    },
    dancar51: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_female^5',
        flag: 1,
    },
    dancar52: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_female^6',
        flag: 1,
    },
    dancar53: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_male^1',
        flag: 1,
    },
    dancar54: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_male^2',
        flag: 1,
    },
    dancar55: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_male^3',
        flag: 1,
    },
    dancar56: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_male^4',
        flag: 1,
    },
    dancar57: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_male^5',
        flag: 1,
    },
    dancar58: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_11_v2_male^6',
        flag: 1,
    },
    dancar59: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_female^1',
        flag: 1,
    },
    dancar60: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_female^2',
        flag: 1,
    },
    dancar61: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_female^3',
        flag: 1,
    },
    dancar62: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_female^4',
        flag: 1,
    },
    dancar63: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_female^5',
        flag: 1,
    },
    dancar64: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_female^6',
        flag: 1,
    },
    dancar65: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_male^1',
        flag: 1,
    },
    dancar66: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_male^2',
        flag: 1,
    },
    dancar67: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_male^3',
        flag: 1,
    },
    dancar68: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_male^4',
        flag: 1,
    },
    dancar69: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_male^5',
        flag: 1,
    },
    dancar70: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v1_male^6',
        flag: 1,
    },
    dancar71: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_female^1',
        flag: 1,
    },
    dancar72: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_female^2',
        flag: 1,
    },
    dancar73: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_female^3',
        flag: 1,
    },
    dancar74: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_female^4',
        flag: 1,
    },
    dancar75: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_female^5',
        flag: 1,
    },
    dancar76: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_female^6',
        flag: 1,
    },
    dancar77: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_male^1',
        flag: 1,
    },
    dancar78: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_male^2',
        flag: 1,
    },
    dancar79: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_male^3',
        flag: 1,
    },
    dancar80: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_male^4',
        flag: 1,
    },
    dancar81: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_male^5',
        flag: 1,
    },
    dancar82: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_13_v2_male^6',
        flag: 1,
    },
    dancar83: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_female^1',
        flag: 1,
    },
    dancar84: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_female^2',
        flag: 1,
    },
    dancar85: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_female^3',
        flag: 1,
    },
    dancar86: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_female^4',
        flag: 1,
    },
    dancar87: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_female^5',
        flag: 1,
    },
    dancar88: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_female^6',
        flag: 1,
    },
    dancar89: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_male^1',
        flag: 1,
    },
    dancar90: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_male^2',
        flag: 1,
    },
    dancar91: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_male^3',
        flag: 1,
    },
    dancar92: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_male^4',
        flag: 1,
    },
    dancar93: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_male^5',
        flag: 1,
    },
    dancar94: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v1_male^6',
        flag: 1,
    },
    dancar95: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_female^1',
        flag: 1,
    },
    dancar96: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_female^2',
        flag: 1,
    },
    dancar97: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_female^3',
        flag: 1,
    },
    dancar98: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_female^4',
        flag: 1,
    },
    dancar99: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_female^5',
        flag: 1,
    },
    dancar100: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_female^6',
        flag: 1,
    },
    dancar101: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_male^1',
        flag: 1,
    },
    dancar102: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_male^2',
        flag: 1,
    },
    dancar103: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_male^3',
        flag: 1,
    },
    dancar104: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_male^4',
        flag: 1,
    },
    dancar105: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_male^5',
        flag: 1,
    },
    dancar106: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_15_v2_male^6',
        flag: 1,
    },
    dancar107: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_female^1',
        flag: 1,
    },
    dancar108: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_female^2',
        flag: 1,
    },
    dancar109: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_female^3',
        flag: 1,
    },
    dancar110: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_female^4',
        flag: 1,
    },
    dancar111: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_female^5',
        flag: 1,
    },
    dancar112: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_female^6',
        flag: 1,
    },
    dancar113: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_male^1',
        flag: 1,
    },
    dancar114: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_male^2',
        flag: 1,
    },
    dancar115: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_male^3',
        flag: 1,
    },
    dancar116: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_male^4',
        flag: 1,
    },
    dancar117: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_male^5',
        flag: 1,
    },
    dancar118: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v1_male^6',
        flag: 1,
    },
    dancar119: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_female^1',
        flag: 1,
    },
    dancar120: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_female^2',
        flag: 1,
    },
    dancar121: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_female^3',
        flag: 1,
    },
    dancar122: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_female^4',
        flag: 1,
    },
    dancar123: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_female^5',
        flag: 1,
    },
    dancar124: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_female^6',
        flag: 1,
    },
    dancar125: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_male^1',
        flag: 1,
    },
    dancar126: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_male^2',
        flag: 1,
    },
    dancar127: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_male^3',
        flag: 1,
    },
    dancar128: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_male^4',
        flag: 1,
    },
    dancar129: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_male^5',
        flag: 1,
    },
    dancar130: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_17_v2_male^6',
        flag: 1,
    },
    dancar131: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_female^1',
        flag: 1,
    },
    dancar132: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_female^2',
        flag: 1,
    },
    dancar133: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_female^3',
        flag: 1,
    },
    dancar134: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_female^4',
        flag: 1,
    },
    dancar135: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_female^5',
        flag: 1,
    },
    dancar136: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_female^6',
        flag: 1,
    },
    dancar137: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_male^1',
        flag: 1,
    },
    dancar138: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_male^2',
        flag: 1,
    },
    dancar139: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_male^3',
        flag: 1,
    },
    dancar140: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_male^4',
        flag: 1,
    },
    dancar141: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_male^5',
        flag: 1,
    },
    dancar142: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v1_male^6',
        flag: 1,
    },
    dancar143: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_female^1',
        flag: 1,
    },
    dancar144: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_female^2',
        flag: 1,
    },
    dancar145: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_female^3',
        flag: 1,
    },
    dancar146: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_female^4',
        flag: 1,
    },
    dancar147: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_female^5',
        flag: 1,
    },
    dancar148: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_female^6',
        flag: 1,
    },
    dancar149: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_male^1',
        flag: 1,
    },
    dancar150: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_male^2',
        flag: 1,
    },
    dancar151: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_male^3',
        flag: 1,
    },
    dancar152: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_male^4',
        flag: 1,
    },
    dancar153: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_male^5',
        flag: 1,
    },
    dancar154: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_09_v2_male^6',
        flag: 1,
    },
    dancar155: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_female^1',
        flag: 1,
    },
    dancar156: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_female^2',
        flag: 1,
    },
    dancar157: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_female^3',
        flag: 1,
    },
    dancar158: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_female^4',
        flag: 1,
    },
    dancar159: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_female^5',
        flag: 1,
    },
    dancar160: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_female^6',
        flag: 1,
    },
    dancar161: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_male^1',
        flag: 1,
    },
    dancar162: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_male^2',
        flag: 1,
    },
    dancar163: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_male^3',
        flag: 1,
    },
    dancar164: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_male^4',
        flag: 1,
    },
    dancar165: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_male^5',
        flag: 1,
    },
    dancar166: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_11_v1_male^6',
        flag: 1,
    },
    dancar167: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_female^1',
        flag: 1,
    },
    dancar168: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_female^2',
        flag: 1,
    },
    dancar169: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_female^3',
        flag: 1,
    },
    dancar170: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_female^4',
        flag: 1,
    },
    dancar171: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_female^5',
        flag: 1,
    },
    dancar172: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_female^6',
        flag: 1,
    },
    dancar173: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_male^1',
        flag: 1,
    },
    dancar174: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_male^2',
        flag: 1,
    },
    dancar175: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_male^3',
        flag: 1,
    },
    dancar176: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_male^4',
        flag: 1,
    },
    dancar177: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_male^5',
        flag: 1,
    },
    dancar178: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_13_v2_male^6',
        flag: 1,
    },
    dancar179: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_female^1',
        flag: 1,
    },
    dancar180: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_female^2',
        flag: 1,
    },
    dancar181: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_female^3',
        flag: 1,
    },
    dancar182: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_female^4',
        flag: 1,
    },
    dancar183: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_female^5',
        flag: 1,
    },
    dancar184: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_female^6',
        flag: 1,
    },
    dancar185: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_male^1',
        flag: 1,
    },
    dancar186: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_male^2',
        flag: 1,
    },
    dancar187: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_male^3',
        flag: 1,
    },
    dancar188: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_male^4',
        flag: 1,
    },
    dancar189: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_male^5',
        flag: 1,
    },
    dancar190: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v1_male^6',
        flag: 1,
    },
    dancar191: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_female^1',
        flag: 1,
    },
    dancar192: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_female^2',
        flag: 1,
    },
    dancar193: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_female^3',
        flag: 1,
    },
    dancar194: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_female^4',
        flag: 1,
    },
    dancar195: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_female^5',
        flag: 1,
    },
    dancar196: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_female^6',
        flag: 1,
    },
    dancar197: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_male^1',
        flag: 1,
    },
    dancar198: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_male^2',
        flag: 1,
    },
    dancar199: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_male^3',
        flag: 1,
    },
    dancar200: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_male^4',
        flag: 1,
    },
    dancar201: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_male^5',
        flag: 1,
    },
    dancar202: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_15_v2_male^6',
        flag: 1,
    },
    dancar203: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_female^1',
        flag: 1,
    },
    dancar204: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_female^2',
        flag: 1,
    },
    dancar205: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_female^3',
        flag: 1,
    },
    dancar206: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_female^4',
        flag: 1,
    },
    dancar207: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_female^5',
        flag: 1,
    },
    dancar208: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_female^6',
        flag: 1,
    },
    dancar209: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_male^1',
        flag: 1,
    },
    dancar210: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_male^2',
        flag: 1,
    },
    dancar211: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_male^3',
        flag: 1,
    },
    dancar212: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_male^4',
        flag: 1,
    },
    dancar213: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_male^5',
        flag: 1,
    },
    dancar214: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v1_male^6',
        flag: 1,
    },
    dancar215: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_female^1',
        flag: 1,
    },
    dancar216: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_female^2',
        flag: 1,
    },
    dancar217: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_female^3',
        flag: 1,
    },
    dancar218: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_female^4',
        flag: 1,
    },
    dancar219: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_female^5',
        flag: 1,
    },
    dancar220: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_female^6',
        flag: 1,
    },
    dancar221: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_male^1',
        flag: 1,
    },
    dancar222: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_male^2',
        flag: 1,
    },
    dancar223: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_male^3',
        flag: 1,
    },
    dancar224: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_male^4',
        flag: 1,
    },
    dancar225: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_male^5',
        flag: 1,
    },
    dancar226: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity',
        anim: 'hi_dance_crowd_17_v2_male^6',
        flag: 1,
    },
    dancar227: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@the_woogie',
        anim: 'the_woogie',
        flag: 1,
    },
    dancar228: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@',
        anim: 'med_center_up',
        flag: 1,
    },
    dancar229: {
        type: 'normal',
        dict: 'anim@amb@casino@mini@dance@dance_solo@female@var_b@',
        anim: 'high_center',
        flag: 1,
    },
    dancar230: {
        type: 'normal',
        dict: 'timetable@tracy@ig_8@idle_b',
        anim: 'idle_d',
        flag: 1,
    },
    dancar231: {
        type: 'normal',
        dict: 'timetable@tracy@ig_5@idle_a',
        anim: 'idle_a',
        flag: 1,
    },
    dancar232: {
        type: 'normal',
        dict: 'anim@amb@nightclub@lazlow@hi_podium@',
        anim: 'danceidle_hi_11_buttwiggle_b_laz',
        flag: 1,
    },
    dancar233: {
        type: 'normal',
        dict: 'move_clown@p_m_two_idles@',
        anim: 'fidget_short_dance',
        flag: 1,
    },
    dancar234: {
        type: 'normal',
        dict: 'move_clown@p_m_zero_idles@',
        anim: 'fidget_short_dance',
        flag: 1,
    },
    dancar235: {
        type: 'normal',
        dict: 'misschinese2_crystalmazemcs1_ig',
        anim: 'dance_flag_t1',
        flag: 1,
    },
    dancar236: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@male@var_b@',
        anim: 'low_center',
        flag: 1,
    },
    dancar237: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_b@',
        anim: 'low_center_down',
        flag: 1,
    },
    dancar238: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@male@var_a@',
        anim: 'low_center',
        flag: 1,
    },
    dancar239: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_b@',
        anim: 'high_center_up',
        flag: 1,
    },
    dancar240: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_b@',
        anim: 'high_center',
        flag: 1,
    },
    dancar241: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@male@var_b@',
        anim: 'high_center_up',
        flag: 1,
    },
    dancar242: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@male@var_a@',
        anim: 'high_center',
        flag: 1,
    },
    dancar243: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@male@var_b@',
        anim: 'high_center_down',
        flag: 1,
    },
    dancar244: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@podium_dancers@',
        anim: 'hi_dance_facedj_17_v2_male^5',
        flag: 1,
    },
    dancar245: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_b@',
        anim: 'low_center',
        flag: 1,
    },
    dancar246: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@',
        anim: 'high_center',
        flag: 1,
    },
    dancar247: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@solomun_entourage@',
        anim: 'mi_dance_facedj_17_v1_female^1',
        flag: 1,
    },
    dancar248: {
        type: 'normal',
        dict: 'anim@amb@casino@mini@dance@dance_solo@female@var_a@',
        anim: 'med_center',
        flag: 1,
    },
    dancar249: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^1',
        flag: 1,
    },
    dancar250: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@',
        anim: 'low_center_down',
        flag: 1,
    },
    dancar251: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@',
        anim: 'low_center',
        flag: 1,
    },
    dancar252: {
        type: 'normal',
        dict: 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@',
        anim: 'high_center_up',
        flag: 1,
    },
    dancar253: {
        type: 'normal',
        dict: 'anim@amb@nightclub@dancers@crowddance_facedj@hi_intensity',
        anim: 'hi_dance_facedj_09_v2_female^3',
        flag: 1,
    },

    //

    sexo: {
        type: 'normal',
        dict: 'rcmpaparazzo_2',
        anim: 'shag_loop_poppy',
        flag: 1,
    },
    sexo2: {
        type: 'normal',
        dict: 'rcmpaparazzo_2',
        anim: 'shag_loop_a',
        flag: 1,
    },
    sexo3: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@air_shagging',
        anim: 'air_shagging',
        flag: 1,
    },
    sentar: { type: 'scenario', dict: 'PROP_HUMAN_SEAT_CHAIR_MP_PLAYER' },
    sentar2: {
        type: 'normal',
        dict: 'amb@world_human_picnic@male@base',
        anim: 'base',
        flag: 1,
    },
    sentar3: {
        type: 'normal',
        dict: 'anim@heists@fleeca_bank@ig_7_jetski_owner',
        anim: 'owner_idle',
        flag: 1,
    },
    sentar4: {
        type: 'normal',
        dict: 'amb@world_human_stupor@male@base',
        anim: 'base',
        flag: 1,
    },
    sentar5: {
        type: 'normal',
        dict: 'amb@world_human_picnic@female@base',
        anim: 'base',
        flag: 1,
    },
    sentar6: {
        type: 'normal',
        dict: 'anim@amb@nightclub@lazlow@lo_alone',
        anim: 'lowalone_base_laz',
        flag: 1,
    },
    sentar7: {
        type: 'normal',
        dict: 'anim@amb@business@bgen@bgen_no_work',
        anim: 'sit_phone_phoneputdown_idle_nowork',
        flag: 1,
    },
    sentar8: {
        type: 'normal',
        dict: 'rcm_barry3',
        anim: 'barry_3_sit_loop',
        flag: 1,
    },
    sentar9: {
        type: 'normal',
        dict: 'amb@world_human_picnic@male@idle_a',
        anim: 'idle_a',
        flag: 1,
    },
    sentar10: {
        type: 'normal',
        dict: 'amb@world_human_picnic@female@idle_a',
        anim: 'idle_a',
        flag: 1,
    },
    sentar11: {
        type: 'normal',
        dict: 'timetable@jimmy@mics3_ig_15',
        anim: 'idle_a_jimmy',
        flag: 1,
    },
    sentar12: {
        type: 'normal',
        dict: 'timetable@jimmy@mics3_ig_15',
        anim: 'mics3_15_base_jimmy',
        flag: 1,
    },
    sentar13: {
        type: 'normal',
        dict: 'amb@world_human_stupor@male@idle_a',
        anim: 'idle_a',
        flag: 1,
    },
    sentar14: {
        type: 'normal',
        dict: 'timetable@tracy@ig_14',
        anim: 'ig_14_base_tracy',
        flag: 1,
    },
    sentar15: {
        type: 'normal',
        dict: 'anim@heists@ornate_bank@hostages@hit',
        anim: 'hit_loop_ped_b',
        flag: 1,
    },
    sentar16: {
        type: 'normal',
        dict: 'anim@heists@ornate_bank@hostages@ped_e',
        anim: 'flinch_loop',
        flag: 1,
    },
    sentar17: {
        type: 'normal',
        dict: 'timetable@ron@ig_5_p3',
        anim: 'ig_5_p3_base',
        flag: 1,
    },
    sentar18: {
        type: 'normal',
        dict: 'timetable@reunited@ig_10',
        anim: 'base_amanda',
        flag: 1,
    },
    sentar19: {
        type: 'normal',
        dict: 'timetable@ron@ig_3_couch',
        anim: 'base',
        flag: 1,
    },
    sentar20: {
        type: 'normal',
        dict: 'timetable@jimmy@mics3_ig_15',
        anim: 'mics3_15_base_tracy',
        flag: 1,
    },
    sentar21: {
        type: 'normal',
        dict: 'timetable@maid@couch',
        anim: 'base',
        flag: 1,
    },
    sentar22: {
        type: 'normal',
        dict: 'timetable@ron@ron_ig_2_alt1',
        anim: 'ig_2_alt1_base',
        flag: 1,
    },
    beijar: {
        type: 'normal',
        dict: 'mp_ped_interaction',
        anim: 'kisses_guy_a',
        flag: 0,
    },
    striper: {
        type: 'normal',
        dict: 'mini@strip_club@idles@stripper',
        anim: 'stripper_idle_02',
        flag: 1,
    },
    escutar: {
        type: 'normal',
        dict: 'mini@safe_cracking',
        anim: 'idle_base',
        flag: 1,
    },
    alongar: {
        type: 'normal',
        dict: 'anim@deathmatch_intros@unarmed',
        anim: 'intro_male_unarmed_e',
        flag: 1,
    },
    dj: {
        type: 'normal',
        dict: 'anim@mp_player_intupperdj',
        anim: 'idle_a',
        flag: 1,
    },
    rock: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationmale@air_guitar',
        anim: 'air_guitar',
        flag: 1,
    },
    rock2: {
        type: 'normal',
        dict: 'mp_player_introck',
        anim: 'mp_player_int_rock',
        flag: 0,
    },
    abracar: {
        type: 'normal',
        dict: 'mp_ped_interaction',
        anim: 'hugs_guy_a',
        flag: 0,
    },
    abracar2: {
        type: 'normal',
        dict: 'mp_ped_interaction',
        anim: 'kisses_guy_b',
        flag: 0,
    },
    peitos: {
        type: 'normal',
        dict: 'mini@strip_club@backroom',
        anim: 'stripper_b_backroom_idle_b',
        flag: 0,
    },
    espernear: {
        type: 'normal',
        dict: 'missfam4leadinoutmcs2',
        anim: 'tracy_loop',
        flag: 1,
    },
    arrumar: {
        type: 'normal',
        dict: 'anim@amb@business@coc@coc_packing_hi',
        anim: 'full_cycle_v1_pressoperator',
        flag: 1,
    },
    bebado: {
        type: 'normal',
        dict: 'missfam5_blackout',
        anim: 'pass_out',
        flag: 0,
    },
    bebado2: {
        type: 'normal',
        dict: 'missheist_agency3astumble_getup',
        anim: 'stumble_getup',
        flag: 0,
    },
    bebado3: {
        type: 'normal',
        dict: 'missfam5_blackout',
        anim: 'vomit',
        flag: 0,
    },
    bebado4: {
        type: 'normal',
        dict: 'random@drunk_driver_1',
        anim: 'drunk_fall_over',
        flag: 0,
    },
    yoga: {
        type: 'normal',
        dict: 'missfam5_yoga',
        anim: 'f_yogapose_a',
        flag: 1,
    },
    yoga2: {
        type: 'normal',
        dict: 'amb@world_human_yoga@male@base',
        anim: 'base_a',
        flag: 1,
    },
    abdominal: {
        type: 'normal',
        dict: 'amb@world_human_sit_ups@male@base',
        anim: 'base',
        flag: 1,
    },
    dormir: {
        type: 'normal',
        dict: 'anim@heists@ornate_bank@hostages@hit',
        anim: 'hit_react_die_loop_ped_a',
        flag: 1,
    },
    dormir2: {
        type: 'normal',
        dict: 'anim@heists@ornate_bank@hostages@hit',
        anim: 'hit_react_die_loop_ped_e',
        flag: 1,
    },
    dormir3: {
        type: 'normal',
        dict: 'anim@heists@ornate_bank@hostages@hit',
        anim: 'hit_react_die_loop_ped_h',
        flag: 1,
    },
    dormir4: { type: 'normal', dict: 'mp_sleep', anim: 'sleep_loop', flag: 1 },
    encostar: {
        type: 'normal',
        dict: 'amb@lo_res_idles',
        anim: 'world_human_lean_male_foot_up_lo_res_base',
        flag: 1,
    },
    estatua: {
        type: 'normal',
        dict: 'amb@world_human_statue@base',
        anim: 'base',
        flag: 1,
    },
    flexao: {
        type: 'normal',
        dict: 'amb@world_human_push_ups@male@base',
        anim: 'base',
        flag: 1,
    },
    malhar2: {
        type: 'normal',
        dict: 'amb@prop_human_muscle_chin_ups@male@base',
        anim: 'base',
        flag: 1,
    },
    plantar: {
        type: 'normal',
        dict: 'amb@world_human_gardener_plant@female@base',
        anim: 'base_female',
        flag: 1,
    },
    plantar2: {
        type: 'normal',
        dict: 'amb@world_human_gardener_plant@female@idle_a',
        anim: 'idle_a_female',
        flag: 1,
    },
    procurar: {
        type: 'normal',
        dict: 'amb@world_human_bum_wash@male@high@base',
        anim: 'base',
        flag: 1,
    },
    trotar: {
        type: 'normal',
        dict: 'amb@world_human_jog_standing@male@fitidle_a',
        anim: 'idle_a',
        flag: 1,
    },
    mecanico: {
        type: 'normal',
        dict: 'amb@world_human_vehicle_mechanic@male@idle_a',
        anim: 'idle_a',
        flag: 1,
    },
    mecanico2: {
        type: 'normal',
        dict: 'mini@repair',
        anim: 'fixing_a_player',
        flag: 1,
    },
    mecanico3: {
        type: 'normal',
        dict: 'mini@repair',
        anim: 'fixing_a_ped',
        flag: 1,
    },
    pullover: {
        type: 'normal',
        dict: 'misscarsteal3pullover',
        anim: 'pull_over_right',
        flag: 0,
    },
    airguitar: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@air_guitar',
        anim: 'air_guitar',
        flag: 1,
    },
    airsynth: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@air_synth',
        anim: 'air_synth',
        flag: 1,
    },
    puto: {
        type: 'normal',
        dict: 'misscarsteal4@actor',
        anim: 'actor_berating_loop',
        flag: 63,
    },
    puto2: {
        type: 'normal',
        dict: 'oddjobs@assassinate@vice@hooker',
        anim: 'argue_a',
        flag: 63,
    },
    puto3: {
        type: 'normal',
        dict: 'mini@triathlon',
        anim: 'want_some_of_this',
        flag: 0,
    },
    unhas: {
        type: 'normal',
        dict: 'anim@amb@clubhouse@bar@drink@idle_a',
        anim: 'idle_a_bartender',
        flag: 63,
    },
    mandarbeijo: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@blow_kiss',
        anim: 'blow_kiss',
        flag: 0,
    },
    mandarbeijo2: {
        type: 'normal',
        dict: 'anim@mp_player_intselfieblow_kiss',
        anim: 'exit',
        flag: 0,
    },
    bale: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationpaired@f_f_sarcastic',
        anim: 'sarcastic_left',
        flag: 1,
    },
    bonzao: {
        type: 'normal',
        dict: 'misscommon@response',
        anim: 'bring_it_on',
        flag: 0,
    },
    cruzarbraco: {
        type: 'normal',
        dict: 'anim@amb@nightclub@peds',
        anim: 'rcmme_amanda1_stand_loop_cop',
        flag: 63,
    },
    cruzarbraco2: {
        type: 'normal',
        dict: 'amb@world_human_hang_out_street@female_arms_crossed@idle_a',
        anim: 'idle_a',
        flag: 63,
    },
    wtf: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@face_palm',
        anim: 'face_palm',
        flag: 49,
    },
    wtf2: {
        type: 'normal',
        dict: 'random@car_thief@agitated@idle_a',
        anim: 'agitated_idle_a',
        flag: 49,
    },
    wtf3: {
        type: 'normal',
        dict: 'missminuteman_1ig_2',
        anim: 'tasered_2',
        flag: 49,
    },
    wtf4: {
        type: 'normal',
        dict: 'anim@mp_player_intupperface_palm',
        anim: 'idle_a',
        flag: 49,
    },
    suicidio: { type: 'normal', dict: 'mp_suicide', anim: 'pistol', flag: 0 },
    suicidio2: { type: 'normal', dict: 'mp_suicide', anim: 'pill', flag: 0 },
    lutar: {
        type: 'normal',
        dict: 'anim@deathmatch_intros@unarmed',
        anim: 'intro_male_unarmed_c',
        flag: 0,
    },
    lutar2: {
        type: 'normal',
        dict: 'anim@deathmatch_intros@unarmed',
        anim: 'intro_male_unarmed_e',
        flag: 0,
    },
    dedo: {
        type: 'normal',
        dict: 'anim@mp_player_intselfiethe_bird',
        anim: 'idle_a',
        flag: 0,
    },
    mochila: { type: 'normal', dict: 'move_m@hiking', anim: 'idle', flag: 63 },
    exercicios: {
        type: 'normal',
        dict: 'timetable@reunited@ig_2',
        anim: 'jimmy_getknocked',
        flag: 63,
    },
    escorar: {
        type: 'normal',
        dict: 'timetable@mime@01_gc',
        anim: 'idle_a',
        flag: 1,
    },
    escorar2: {
        type: 'normal',
        dict: 'misscarstealfinale',
        anim: 'packer_idle_1_trevor',
        flag: 1,
    },
    escorar3: {
        type: 'normal',
        dict: 'misscarstealfinalecar_5_ig_1',
        anim: 'waitloop_lamar',
        flag: 1,
    },
    escorar4: {
        type: 'normal',
        dict: 'rcmjosh2',
        anim: 'josh_2_intp1_base',
        flag: 1,
    },
    meditar: {
        type: 'normal',
        dict: 'rcmcollect_paperleadinout',
        anim: 'meditiate_idle',
        flag: 1,
    },
    meditar2: {
        type: 'normal',
        dict: 'rcmepsilonism3',
        anim: 'ep_3_rcm_marnie_meditating',
        flag: 1,
    },
    meditar3: {
        type: 'normal',
        dict: 'rcmepsilonism3',
        anim: 'base_loop',
        flag: 1,
    },
    meleca2: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@nose_pick',
        anim: 'nose_pick',
        flag: 0,
    },
    cortaessa: {
        type: 'normal',
        dict: 'gestures@m@standing@casual',
        anim: 'gesture_no_way',
        flag: 0,
    },
    meleca3: {
        type: 'normal',
        dict: 'move_p_m_two_idles@generic',
        anim: 'fidget_sniff_fingers',
        flag: 49,
    },
    bebado5: {
        type: 'normal',
        dict: 'misscarsteal4@actor',
        anim: 'stumble',
        flag: 0,
    },
    joia: {
        type: 'normal',
        dict: 'anim@mp_player_intincarthumbs_uplow@ds',
        anim: 'enter',
        flag: 0,
    },
    joia2: {
        type: 'normal',
        dict: 'anim@mp_player_intselfiethumbs_up',
        anim: 'idle_a',
        flag: 0,
    },
    yeah: {
        type: 'normal',
        dict: 'anim@mp_player_intupperair_shagging',
        anim: 'idle_a',
        flag: 0,
    },
    assobiar: { type: 'normal', dict: 'taxi_hail', anim: 'hail_taxi', flag: 0 },
    carona: {
        type: 'normal',
        dict: 'random@hitch_lift',
        anim: 'idle_f',
        flag: 49,
    },
    estatua2: {
        type: 'normal',
        dict: 'fra_0_int-1',
        anim: 'cs_lamardavis_dual-1',
        flag: 1,
    },
    estatua3: {
        type: 'normal',
        dict: 'club_intro2-0',
        anim: 'csb_englishdave_dual-0',
        flag: 1,
    },
    dormir5: {
        type: 'normal',
        dict: 'missarmenian2',
        anim: 'drunk_loop',
        flag: 1,
    },
    colher: {
        type: 'normal',
        dict: 'creatures@rottweiler@tricks',
        anim: 'petting_franklin',
        flag: 0,
    },
    rastejar: {
        type: 'normal',
        dict: 'move_injured_ground',
        anim: 'front_loop',
        flag: 1,
    },
    pirueta: {
        type: 'normal',
        dict: 'anim@arena@celeb@flat@solo@no_props',
        anim: 'cap_a_player_a',
        flag: 0,
    },
    pirueta2: {
        type: 'normal',
        dict: 'anim@arena@celeb@flat@solo@no_props',
        anim: 'flip_a_player_a',
        flag: 0,
    },
    fodase: {
        type: 'normal',
        dict: 'anim@arena@celeb@podium@no_prop',
        anim: 'flip_off_a_1st',
        flag: 0,
    },
    taco: {
        type: 'normal',
        dict: 'anim@arena@celeb@flat@solo@no_props',
        anim: 'slugger_a_player_a',
        flag: 0,
    },
    onda: {
        type: 'normal',
        dict: 'anim@mp_player_intupperfind_the_fish',
        anim: 'idle_a',
        flag: 1,
    },
    alongar3: {
        type: 'normal',
        dict: 'mini@triathlon',
        anim: 'idle_f',
        flag: 1,
    },
    alongar4: {
        type: 'normal',
        dict: 'mini@triathlon',
        anim: 'idle_d',
        flag: 1,
    },
    alongar5: {
        type: 'normal',
        dict: 'rcmfanatic1maryann_stretchidle_b',
        anim: 'idle_e',
        flag: 1,
    },
    lutar3: {
        type: 'normal',
        dict: 'rcmextreme2',
        anim: 'loop_punching',
        flag: 63,
    },
    heroi: { type: 'normal', dict: 'rcmbarry', anim: 'base', flag: 63 },
    boboalegre: {
        type: 'normal',
        dict: 'rcm_barry2',
        anim: 'clown_idle_0',
        flag: 0,
    },
    boboalegre2: {
        type: 'normal',
        dict: 'rcm_barry2',
        anim: 'clown_idle_1',
        flag: 0,
    },
    boboalegre3: {
        type: 'normal',
        dict: 'rcm_barry2',
        anim: 'clown_idle_2',
        flag: 0,
    },
    boboalegre4: {
        type: 'normal',
        dict: 'rcm_barry2',
        anim: 'clown_idle_3',
        flag: 0,
    },
    boboalegre4: {
        type: 'normal',
        dict: 'rcm_barry2',
        anim: 'clown_idle_6',
        flag: 0,
    },
    meditar4: {
        type: 'normal',
        dict: 'timetable@amanda@ig_4',
        anim: 'ig_4_base',
        flag: 1,
    },
    passaro: {
        type: 'normal',
        dict: 'random@peyote@bird',
        anim: 'wakeup',
        flag: 0,
    },
    cachorro: {
        type: 'normal',
        dict: 'random@peyote@dog',
        anim: 'wakeup',
        flag: 0,
    },
    karate: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@karate_chops',
        anim: 'karate_chops',
        flag: 0,
    },
    karate2: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationmale@karate_chops',
        anim: 'karate_chops',
        flag: 0,
    },
    ameacar: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationmale@cut_throat',
        anim: 'cut_throat',
        flag: 0,
    },
    ameacar2: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@cut_throat',
        anim: 'cut_throat',
        flag: 0,
    },
    boxe: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationmale@shadow_boxing',
        anim: 'shadow_boxing',
        flag: 0,
    },
    boxe2: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationfemale@shadow_boxing',
        anim: 'shadow_boxing',
        flag: 0,
    },
    mamamia: {
        type: 'normal',
        dict: 'anim@mp_player_intcelebrationmale@finger_kiss',
        anim: 'finger_kiss',
        flag: 49,
    },
    louco: {
        type: 'normal',
        dict: 'anim@mp_player_intincaryou_locobodhi@ds',
        anim: 'idle_a',
        flag: 63,
    },
    xiu: {
        type: 'normal',
        dict: 'anim@mp_player_intincarshushbodhi@ds',
        anim: 'idle_a_fp',
        flag: 63,
    },
    cruzar: {
        type: 'normal',
        dict: 'amb@world_human_cop_idles@female@idle_b',
        anim: 'idle_e',
        flag: 63,
    },
    peace: {
        type: 'normal',
        dict: 'mp_player_int_upperpeace_sign',
        anim: 'mp_player_int_peace_sign',
        flag: 48,
    },
    deitar: {
        type: 'normal',
        dict: 'amb@world_human_sunbathe@female@back@idle_a',
        anim: 'idle_a',
        flag: 0,
    },
    deitar2: {
        type: 'normal',
        dict: 'amb@world_human_sunbathe@female@front@idle_a',
        anim: 'idle_a',
        flag: 0,
    },
    deitar3: {
        type: 'normal',
        dict: 'amb@world_human_sunbathe@male@back@idle_a',
        anim: 'idle_a',
        flag: 0,
    },
    deitar4: {
        type: 'normal',
        dict: 'amb@world_human_sunbathe@male@front@idle_a',
        anim: 'idle_a',
        flag: 0,
    },
    deitar5: {
        type: 'normal',
        dict: 'mini@cpr@char_b@cpr_str',
        anim: 'cpr_kol_idle',
        flag: 48,
    },
    debrucar: {
        type: 'normal',
        dict: 'amb@prop_human_bum_shopping_cart@male@base',
        anim: 'base',
        flag: 0,
    },
    //scenario

    bixa: { type: 'scenario', dict: 'WORLD_HUMAN_PROSTITUTE_LOW_CLASS' },
    cerveja: { type: 'scenario', dict: 'WORLD_HUMAN_PARTYING' },
    churrasco: { type: 'scenario', dict: 'PROP_HUMAN_BBQ' },
    consertar: { type: 'scenario', dict: 'WORLD_HUMAN_WELDING' },
    fumar: { type: 'scenario', dict: 'WORLD_HUMAN_SMOKING' },
    fumar2: { type: 'sscenario', dict: 'WORLD_HUMAN_PROSTITUTE_HIGH_CLASS' },
    fumar3: { type: 'scenario', dict: 'WORLD_HUMAN_AA_SMOKE' },
    fumar4: { type: 'scenario', dict: 'WORLD_HUMAN_SMOKING_POT' },
    tragar: { type: 'scenario', dict: 'WORLD_HUMAN_DRUG_DEALER' },
    esquentar: { type: 'scenario', dict: 'WORLD_HUMAN_STAND_FIRE' },

    //car

    sexo4: {
        type: 'car',
        dict: 'oddjobs@towing',
        anim: 'm_blow_job_loop',
        flag: 1,
    },
    sexo5: {
        type: 'car',
        dict: 'oddjobs@towing',
        anim: 'f_blow_job_loop',
        flag: 1,
    },
    sexo6: {
        type: 'car',
        dict: 'mini@prostitutes@sexlow_veh',
        anim: 'low_car_sex_loop_female',
        flag: 1,
    },

    //prop
    martelo: {
        type: 'prop',
        dict: 'amb@world_human_hammering@male@base',
        anim: 'base',
        prop: 'prop_tool_hammer',
        flag: 49,
        bone: 28422,
    },
    prebeber: {
        type: 'prop',
        dict: 'amb@code_human_wander_drinking@beer@male@base',
        anim: 'static',
        prop: 'prop_fib_coffee',
        flag: 49,
        bone: 28422,
    },
    prebeber2: {
        type: 'prop',
        dict: 'amb@code_human_wander_drinking@beer@male@base',
        anim: 'static',
        prop: 'prop_ld_flow_bottle',
        flag: 49,
        bone: 28422,
    },
    prebeber3: {
        type: 'prop',
        dict: 'amb@code_human_wander_drinking@beer@male@base',
        anim: 'static',
        prop: 'prop_cs_bs_cup',
        flag: 49,
        bone: 28422,
    },
    radio2: {
        type: 'prop',
        prop: 'prop_boombox_01',
        flag: 50,
        bone: 57005,
        height: 0.3,
        pos1: 0,
        pos2: 0,
        pos3: 0,
    },
    bolsa: {
        type: 'prop',
        prop: 'prop_ld_case_01',
        flag: 50,
        bone: 57005,
        height: 0.16,
        pos1: 0,
        pos2: 0,
        pos3: 0,
    },
    bolsa2: {
        type: 'prop',
        prop: 'prop_ld_case_01_s',
        flag: 50,
        bone: 57005,
        height: 0.16,
        pos1: 0,
        pos2: 0,
        pos3: 0,
    },
    bolsa3: {
        type: 'prop',
        prop: 'prop_security_case_01',
        flag: 50,
        bone: 57005,
        height: 0.16,
        pos1: 0,
        pos2: -0.01,
        pos3: 0,
    },
    bolsa4: {
        type: 'prop',
        prop: 'w_am_case',
        flag: 50,
        bone: 57005,
        height: 0.08,
        pos1: 0,
        pos2: 0,
        pos3: 0,
    },
    caixa2: {
        type: 'prop',
        prop: 'prop_tool_box_04',
        flag: 50,
        bone: 57005,
        height: 0.45,
        pos1: 0,
        pos2: 0.05,
        pos3: 0,
    },
    lixo: {
        type: 'prop',
        prop: 'prop_cs_rub_binbag_01',
        flag: 50,
        bone: 57005,
        height: 0.11,
        pos1: 0,
        pos2: 0.0,
        pos3: 0,
    },
    prebeber: {
        type: 'prop',
        dict: 'amb@code_human_wander_drinking@beer@male@base',
        anim: 'static',
        prop: 'prop_fib_coffee',
        flag: 49,
        bone: 28422,
    },
    prebeber2: {
        type: 'prop',
        dict: 'amb@code_human_wander_drinking@beer@male@base',
        anim: 'static',
        prop: 'prop_ld_flow_bottle',
        flag: 49,
        bone: 28422,
    },
    prebeber3: {
        type: 'prop',
        dict: 'amb@code_human_wander_drinking@beer@male@base',
        anim: 'static',
        prop: 'prop_cs_bs_cup',
        flag: 49,
        bone: 28422,
    },
    sinalizar: {
        type: 'prop',
        dict: 'amb@world_human_car_park_attendant@male@base',
        anim: 'base',
        prop: 'prop_parking_wand_01',
        flag: 49,
        bone: 28422,
    },
    placa: {
        type: 'prop',
        dict: 'amb@world_human_bum_freeway@male@base',
        anim: 'base',
        prop: 'prop_beggers_sign_01',
        flag: 49,
        bone: 28422,
    },
    placa2: {
        type: 'prop',
        dict: 'amb@world_human_bum_freeway@male@base',
        anim: 'base',
        prop: 'prop_beggers_sign_03',
        flag: 49,
        bone: 28422,
    },
    placa3: {
        type: 'prop',
        dict: 'amb@world_human_bum_freeway@male@base',
        anim: 'base',
        prop: 'prop_beggers_sign_04',
        flag: 49,
        bone: 28422,
    },
    ligar: {
        type: 'prop',
        dict: 'cellphone@',
        anim: 'cellphone_call_in',
        prop: 'prop_amb_phone',
        flag: 50,
        bone: 28422,
    },
    cafe: {
        type: 'prop',
        dict: 'amb@world_human_aa_coffee@base',
        anim: 'base',
        prop: 'prop_fib_coffee',
        flag: 50,
        bone: 28422,
    },
    cafe2: {
        type: 'prop',
        dict: 'amb@world_human_aa_coffee@idle_a',
        anim: 'idle_a',
        prop: 'prop_fib_coffee',
        flag: 49,
        bone: 28422,
    },
    caixa: {
        type: 'prop',
        dict: 'anim@heists@box_carry@',
        anim: 'idle',
        prop: 'hei_prop_heist_box',
        flag: 50,
        bone: 28422,
    },
    chuva: {
        type: 'prop',
        dict: 'amb@world_human_drinking@coffee@male@base',
        anim: 'base',
        prop: 'p_amb_brolly_01',
        flag: 50,
        bone: 28422,
    },
    chuva2: {
        type: 'prop',
        dict: 'amb@world_human_drinking@coffee@male@base',
        anim: 'base',
        prop: 'p_amb_brolly_01_s',
        flag: 50,
        bone: 28422,
    },
    comer: {
        type: 'prop',
        dict: 'amb@code_human_wander_eating_donut@male@idle_a',
        anim: 'idle_c',
        prop: 'prop_cs_burger_01',
        flag: 49,
        bone: 28422,
    },
    comer2: {
        type: 'prop',
        dict: 'amb@code_human_wander_eating_donut@male@idle_a',
        anim: 'idle_c',
        prop: 'prop_cs_hotdog_01',
        flag: 49,
        bone: 28422,
    },
    comer3: {
        type: 'prop',
        dict: 'amb@code_human_wander_eating_donut@male@idle_a',
        anim: 'idle_c',
        prop: 'prop_amb_donut',
        flag: 49,
        bone: 28422,
    },
    beber: {
        type: 'prop',
        dict: 'amb@world_human_drinking@beer@male@idle_a',
        anim: 'idle_a',
        prop: 'p_cs_bottle_01',
        flag: 49,
        bone: 28422,
    },
    beber2: {
        type: 'prop',
        dict: 'amb@world_human_drinking@beer@male@idle_a',
        anim: 'idle_a',
        prop: 'prop_energy_drink',
        flag: 49,
        bone: 28422,
    },
    beber3: {
        type: 'prop',
        dict: 'amb@world_human_drinking@beer@male@idle_a',
        anim: 'idle_a',
        prop: 'prop_amb_beer_bottle',
        flag: 49,
        bone: 28422,
    },
    beber4: {
        type: 'prop',
        dict: 'amb@world_human_drinking@beer@male@idle_a',
        anim: 'idle_a',
        prop: 'p_whiskey_notop',
        flag: 49,
        bone: 28422,
    },
    beber5: {
        type: 'prop',
        dict: 'amb@world_human_drinking@beer@male@idle_a',
        anim: 'idle_a',
        prop: 'prop_beer_logopen',
        flag: 49,
        bone: 28422,
    },
    beber6: {
        type: 'prop',
        dict: 'amb@world_human_drinking@beer@male@idle_a',
        anim: 'idle_a',
        prop: 'prop_beer_blr',
        flag: 49,
        bone: 28422,
    },
    beber7: {
        type: 'prop',
        dict: 'amb@world_human_drinking@beer@male@idle_a',
        anim: 'idle_a',
        prop: 'prop_ld_flow_bottle',
        flag: 49,
        bone: 28422,
    },
    varrer: {
        type: 'prop',
        dict: 'amb@world_human_janitor@male@idle_a',
        anim: 'idle_a',
        prop: 'prop_tool_broom',
        flag: 49,
        bone: 28422,
    },
    musica: {
        type: 'prop',
        dict: 'amb@world_human_musician@guitar@male@base',
        anim: 'base',
        prop: 'prop_el_guitar_01',
        flag: 49,
        bone: 60309,
    },
    musica2: {
        type: 'prop',
        dict: 'amb@world_human_musician@guitar@male@base',
        anim: 'base',
        prop: 'prop_el_guitar_02',
        flag: 49,
        bone: 60309,
    },
    musica3: {
        type: 'prop',
        dict: 'amb@world_human_musician@guitar@male@base',
        anim: 'base',
        prop: 'prop_el_guitar_03',
        flag: 49,
        bone: 60309,
    },
    musica4: {
        type: 'prop',
        dict: 'amb@world_human_musician@guitar@male@base',
        anim: 'base',
        prop: 'prop_acc_guitar_01',
        flag: 49,
        bone: 60309,
    },
    camera: {
        type: 'prop',
        dict: 'amb@world_human_paparazzi@male@base',
        anim: 'base',
        prop: 'prop_pap_camera_01',
        flag: 49,
        bone: 28422,
    },
    camera2: {
        type: 'prop',
        dict: 'missfinale_c2mcs_1',
        anim: 'fin_c2_mcs_1_camman',
        prop: 'prop_v_cam_01',
        flag: 49,
        bone: 28422,
    },
    prancheta: {
        type: 'prop',
        dict: 'amb@world_human_clipboard@male@base',
        anim: 'base',
        prop: 'p_amb_clipboard_01',
        flag: 50,
        bone: 60309,
    },
    mapa: {
        type: 'prop',
        dict: 'amb@world_human_clipboard@male@base',
        anim: 'base',
        prop: 'prop_tourist_map_01',
        flag: 50,
        bone: 60309,
    },
    anotar: {
        type: 'prop',
        dict: 'amb@medic@standing@timeofdeath@base',
        anim: 'base',
        prop: 'prop_notepad_01',
        flag: 49,
        bone: 60309,
    },

    radio: {
        type: 'prop',
        dict: 'random@arrests',
        anim: 'generic_radio_chatter',
        prop: 'prop_cs_hand_radio',
        height: 0.04,
        pos1: 0.0,
        pos2: 0.0,
        pos3: -50.0,
        pos4: 180.0,
        pos5: 30.0,
        flag: 49,
        bone: 60309,
    },
};

export const walkStyles = {
    homem: { set: 'move_m@confident' },
    mulher: { set: 'move_f@heels@c' },
    depressivo: { set: 'move_m@depressed@a' },
    depressiva: { set: 'move_f@depressed@a' },
    empresario: { set: 'move_m@business@a' },
    empresaria: { set: 'move_f@business@a' },
    determinado: { set: 'move_m@brave@a' },
    descontraido: { set: 'move_m@casual@a' },
    farto: { set: 'move_m@fat@a' },
    estiloso: { set: 'move_m@hipster@a' },
    nervoso: { set: 'move_m@hurry@a' },
    desleixado: { set: 'move_m@hobo@a' },
    infeliz: { set: 'move_m@sad@a' },
    musculoso: { set: 'move_m@muscle@a' },
    desligado: { set: 'move_m@shadyped@a' },
    fadiga: { set: 'move_m@buzzed' },
    apressado: { set: 'move_m@hurry_butch@a' },
    descolado: { set: 'move_m@money' },
    corridinha: { set: 'move_m@quick' },
    piriguete: { set: 'move_f@maneater' },
    petulante: { set: 'move_f@sassy' },
    arrogante: { set: 'move_f@arrogant@a' },
    bebado: { set: 'move_m@drunk@slightlydrunk' },
    bebado2: { set: 'move_m@drunk@verydrunk' },
    bebado3: { set: 'move_m@drunk@moderatedrunk' },
    irritado: { set: 'move_m@fire' },
    intimidado: { set: 'move_m@intimidation@cop@unarmed' },
    poderosa: { set: 'move_f@handbag' },
    chateado: { set: 'move_f@injured' },
    estilosa: { set: 'move_f@posh@' },
    sensual: { set: 'move_f@sexy@a' },
};
