export const Webhooks = {
    default: '',
    testwebhook: '',
    playermoney: '',
    playerinventory: '',
    robbing: '',
    cuffing: '',
    drop: '',
    trunk: '',
    stash: '',
    glovebox: '',
    banking: '',
    vehicleshop: '',
    vehicleupgrades: '',
    shops: '',
    dealers: '',
    storerobbery: '',
    bankrobbery: '',
    powerplants: '',
    death: '',
    joinleave: '',
    ooc: '',
    report: '',
    me: '',
    pmelding: '',
    112: '',
    bans: '',
    anticheat: '',
    weather: '',
    moneysafes: '',
    bennys: '',
    bossmenu: '',
    robbery: '',
    casino: '',
    traphouse: '',
    911: '',
    palert: '',
    house: '',
};

export const Colors = {
    default: 25087,
    blue: 25087,
    green: 762640,
    white: 16777215,
    black: 0,
    orange: 16743168,
    lightgreen: 65309,
    yellow: 15335168,
    turqois: 62207,
    pink: 16711900,
    red: 16711680,
};
