import * as alt from 'alt-server';

export const MARKET_LIST = [
    {
        x: -46.2593,
        y: -1757.91,
        z: 28.4147,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 52.1867,
        },
    },
    {
        x: 372.857,
        y: 328.021,
        z: 102.553,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -109.819,
        },
    },
    {
        x: -1222.44,
        y: -908.663,
        z: 11.312,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 30.291,
        },
    },
    {
        x: -705.626,
        y: -914.611,
        z: 18.2036,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 85.726,
        },
    },
    {
        x: 24.2505,
        y: -1345.08,
        z: 28.4821,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -93.251,
        },
    },
    {
        x: 1134.06,
        y: -981.811,
        z: 45.399,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -86.032,
        },
    },
    {
        x: 1164.83,
        y: -323.617,
        z: 68.197,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 92.38,
        },
    },
    {
        x: -1485.96,
        y: -377.96,
        z: 39.1479,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 129.749,
        },
    },
    {
        x: -2966.52,
        y: 390.435,
        z: 14.041,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 88.193,
        },
    },
    {
        x: -3040.58,
        y: 583.938,
        z: 6.897,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 16.129,
        },
    },
    {
        x: -3244.03,
        y: 1000.13,
        z: 11.817,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 10.731,
        },
    },
    {
        x: 1728.7,
        y: 6417.34,
        z: 34.0256,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -119.807,
        },
    },
    {
        x: 1697.05,
        y: 4922.95,
        z: 41.052,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -41.935,
        },
    },
    {
        x: 1959.18,
        y: 3741.01,
        z: 31.3297,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -63.105,
        },
    },
    {
        x: 1392.18,
        y: 3606.2,
        z: 33.975,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -164.534,
        },
    },
    {
        x: 2676.45,
        y: 3280.27,
        z: 54.228,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -29.164,
        },
    },
    {
        x: 1166.47,
        y: 2710.79,
        z: 37.142,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 173.485,
        },
    },
    {
        x: 549.257,
        y: 2669.63,
        z: 41.153,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 96.043,
        },
    },
    {
        x: 2555.49,
        y: 380.874,
        z: 108.608,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: -5.194,
        },
    },
    {
        x: -1819.52,
        y: 793.609,
        z: 137.096,
        type: 'market',
        isServer: false,
        eventName: 'Market:open',
        blip: {
            sprite: 52,
            color: 2,
        },
        ped: {
            pedType: 3,
            modelHash: alt.hash('csb_isldj_04'),
            pedHeading: 126.524,
        },
    },
];
