CREATE TABLE `phone_message` (
	`id` INT(100) NOT NULL AUTO_INCREMENT,
	`chat_id` INT(10) NULL DEFAULT NULL,
	`owner` VARCHAR(10) NULL DEFAULT NULL ,
	`type` VARCHAR(20) NULL DEFAULT NULl,
	`message` VARCHAR(300) NULL DEFAULT NULl,
	`created` DATETIME,
	`read`  INT(1) NOT NULL DEFAULT 0,
	`deleted` INT(1) NOT NULL DEFAULT 0,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;


CREATE TABLE `phone_contact` (
	`id` INT(5) NOT NULL AUTO_INCREMENT,
	`ssn` VARCHAR(20) NULL DEFAULT NULL ,
	`contact` VARCHAR(1000) NULL DEFAULT NULl,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
CREATE TABLE `phone_recent` (
	`id` INT(5) NOT NULL AUTO_INCREMENT,
	`ssn` VARCHAR(20) NULL DEFAULT NULL ,
	`recent` VARCHAR(1000) NULL DEFAULT NULl,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;
CREATE TABLE `phone_history_message` (
	`id` INT(5) NOT NULL AUTO_INCREMENT,
	`ssn` VARCHAR(20) NULL DEFAULT NULL ,
	`history_message` VARCHAR(1000) NULL DEFAULT NULl,
	PRIMARY KEY (`id`) USING BTREE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=3
;



